# These are supported funding model platforms

github: 'dy55'
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge: 
# liberapay:
# issuehunt:
# otechie:
custom: [https://paypal.me/dy55, https://github.com/dy55/Silk-Carousel/blob/master/.github/info/alipayQR_dy55.jpg]